FROM amazoncorretto:17 AS builder
COPY ./ ./
RUN ./gradlew :metrics-agent:build

FROM amazoncorretto:17
RUN mkdir /app
COPY --from=builder metrics-agent/build/libs/metrics-agent-0.0.1-SNAPSHOT.jar /app/app.jar
ENTRYPOINT java -jar /app/app.jar