FROM amazoncorretto:17 AS builder
COPY ./ ./
RUN ./gradlew :metrics-api:build -x test

FROM amazoncorretto:17
RUN mkdir /app
COPY --from=builder metrics-api/build/libs/metrics-api-0.0.1-SNAPSHOT.jar /app/app.jar
ENTRYPOINT java -jar /app/app.jar